### ISSUE TITLE
When running your code, some error happened  

### ISSUE THREAD

**Issue by sshzhang** [riannevdberg/gc-mc#4]
Hello author:
  the environement is    python 3.6 ,   tensorflower 1.4   but, when run your code , some error happens. Here is the specific errors.

Settings:
{'dataset': 'flixster', 'data_seed': 1234, 'feat_hidden': 64, 'write_summary': False, 'norm_symmetric': False, 'dropout': 0.7, 'features': True, 'epochs': 200, 'summaries_dir': 'logs/2018-11-15_15:03:52.631584', 'accumulation': 'stack', 'num_basis_functions': 2, 'learning_rate': 0.01, 'testing': True, 'hidden': [500, 75]} 

number of users =  2341
number of item =  2956
Traceback (most recent call last):
  File "train.py", line 150, in <module>
    test_u_indices, test_v_indices, class_values = load_data_monti(DATASET, TESTING)
  File "/home/zxj/PycharmProjects/gc-mc/gcmc/preprocessing.py", line 274, in load_data_monti
    np.random.shuffle(rand_idx)
  File "mtrand.pyx", line 4852, in mtrand.RandomState.shuffle
  File "mtrand.pyx", line 4855, in mtrand.RandomState.shuffle
TypeError: 'range' object does not support item assignment
Can you help me solved this problems! Thank you very much!

**Comment by riannevdberg** [comment]
Hello! Thank you for taking an interest in our work :) Our code is written with python 2.7, so I suspect that when you run it with 3.6 the version difference causes the issue you observe. I will clarify in the README file that it's written with python 2.7.
